# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_audit <- function(x, ids, unit_ids, labels, paired_design, k, budget, direction, selected, max_nodes, max_scenarios, witness_trials = 8L, use_bounds = TRUE, influence_order = FALSE) {
    .Call(`_extremarank_cpp_audit`, x, ids, unit_ids, labels, paired_design, k, budget, direction, selected, max_nodes, max_scenarios, witness_trials, use_bounds, influence_order)
}

cpp_extrema <- function(values, included, choose) {
    .Call(`_extremarank_cpp_extrema`, values, included, choose)
}

cpp_evaluate <- function(x, ids, labels, paired_design, direction, deleted) {
    .Call(`_extremarank_cpp_evaluate`, x, ids, labels, paired_design, direction, deleted)
}

cpp_bounds <- function(x, ids, labels, paired_design, included, optional, needed) {
    .Call(`_extremarank_cpp_bounds`, x, ids, labels, paired_design, included, optional, needed)
}

cpp_diagnostics <- function(x, ids, unit_ids, labels, paired_design, k, direction, max_diagnostics = 1000000L) {
    .Call(`_extremarank_cpp_diagnostics`, x, ids, unit_ids, labels, paired_design, k, direction, max_diagnostics)
}

cpp_plan <- function(labels, paired_design, budget) {
    .Call(`_extremarank_cpp_plan`, labels, paired_design, budget)
}

cpp_block_plan <- function(a, b, budget, paired_design) {
    .Call(`_extremarank_cpp_block_plan`, a, b, budget, paired_design)
}

cpp_remaining <- function(planned, completed) {
    .Call(`_extremarank_cpp_remaining`, planned, completed)
}
