# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_audit <- function(x, ids, unit_ids, labels, paired_design, k, budget, direction, selected, max_nodes, max_scenarios, witness_trials = 8L, use_bounds = TRUE) {
    .Call(`_extremarank_cpp_audit`, x, ids, unit_ids, labels, paired_design, k, budget, direction, selected, max_nodes, max_scenarios, witness_trials, use_bounds)
}

cpp_extrema <- function(values, included, choose) {
    .Call(`_extremarank_cpp_extrema`, values, included, choose)
}

cpp_evaluate <- function(x, ids, labels, paired_design, direction, deleted) {
    .Call(`_extremarank_cpp_evaluate`, x, ids, labels, paired_design, direction, deleted)
}

cpp_bounds <- function(x, ids, labels, paired_design, included, optional, needed) {
    .Call(`_extremarank_cpp_bounds`, x, ids, labels, paired_design, included, optional, needed)
}

cpp_diagnostics <- function(x, ids, unit_ids, labels, paired_design, k, direction) {
    .Call(`_extremarank_cpp_diagnostics`, x, ids, unit_ids, labels, paired_design, k, direction)
}
