// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_audit
List cpp_audit(NumericMatrix x, CharacterVector ids, CharacterVector unit_ids, IntegerVector labels, bool paired_design, int k, int budget, std::string direction, IntegerVector selected, int max_nodes, int max_scenarios, int witness_trials, bool use_bounds);
RcppExport SEXP _extremarank_cpp_audit(SEXP xSEXP, SEXP idsSEXP, SEXP unit_idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP kSEXP, SEXP budgetSEXP, SEXP directionSEXP, SEXP selectedSEXP, SEXP max_nodesSEXP, SEXP max_scenariosSEXP, SEXP witness_trialsSEXP, SEXP use_boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type unit_ids(unit_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type budget(budgetSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type selected(selectedSEXP);
    Rcpp::traits::input_parameter< int >::type max_nodes(max_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type max_scenarios(max_scenariosSEXP);
    Rcpp::traits::input_parameter< int >::type witness_trials(witness_trialsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bounds(use_boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_audit(x, ids, unit_ids, labels, paired_design, k, budget, direction, selected, max_nodes, max_scenarios, witness_trials, use_bounds));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extrema
List cpp_extrema(NumericVector values, NumericVector included, int choose);
RcppExport SEXP _extremarank_cpp_extrema(SEXP valuesSEXP, SEXP includedSEXP, SEXP chooseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type included(includedSEXP);
    Rcpp::traits::input_parameter< int >::type choose(chooseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extrema(values, included, choose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_evaluate
List cpp_evaluate(NumericMatrix x, CharacterVector ids, IntegerVector labels, bool paired_design, std::string direction, IntegerVector deleted);
RcppExport SEXP _extremarank_cpp_evaluate(SEXP xSEXP, SEXP idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP directionSEXP, SEXP deletedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type deleted(deletedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_evaluate(x, ids, labels, paired_design, direction, deleted));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bounds
List cpp_bounds(NumericMatrix x, CharacterVector ids, IntegerVector labels, bool paired_design, IntegerVector included, IntegerVector optional, IntegerVector needed);
RcppExport SEXP _extremarank_cpp_bounds(SEXP xSEXP, SEXP idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP includedSEXP, SEXP optionalSEXP, SEXP neededSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type included(includedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type optional(optionalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type needed(neededSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bounds(x, ids, labels, paired_design, included, optional, needed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_diagnostics
List cpp_diagnostics(NumericMatrix x, CharacterVector ids, CharacterVector unit_ids, IntegerVector labels, bool paired_design, int k, std::string direction);
RcppExport SEXP _extremarank_cpp_diagnostics(SEXP xSEXP, SEXP idsSEXP, SEXP unit_idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP kSEXP, SEXP directionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type unit_ids(unit_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_diagnostics(x, ids, unit_ids, labels, paired_design, k, direction));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_extremarank_cpp_audit", (DL_FUNC) &_extremarank_cpp_audit, 13},
    {"_extremarank_cpp_extrema", (DL_FUNC) &_extremarank_cpp_extrema, 3},
    {"_extremarank_cpp_evaluate", (DL_FUNC) &_extremarank_cpp_evaluate, 6},
    {"_extremarank_cpp_bounds", (DL_FUNC) &_extremarank_cpp_bounds, 7},
    {"_extremarank_cpp_diagnostics", (DL_FUNC) &_extremarank_cpp_diagnostics, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_extremarank(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
