// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_validate_counts
bool cpp_validate_counts(SEXP x);
RcppExport SEXP _extremarank_cpp_validate_counts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_validate_counts(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pseudobulk_native
List cpp_pseudobulk_native(SEXP x, IntegerVector unit, int n_units);
RcppExport SEXP _extremarank_cpp_pseudobulk_native(SEXP xSEXP, SEXP unitSEXP, SEXP n_unitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pseudobulk_native(x, unit, n_units));
    return rcpp_result_gen;
END_RCPP
}
// cpp_group_codes
List cpp_group_codes(List codes);
RcppExport SEXP _extremarank_cpp_group_codes(SEXP codesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type codes(codesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_group_codes(codes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_backend_info
List cpp_backend_info();
RcppExport SEXP _extremarank_cpp_backend_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_backend_info());
    return rcpp_result_gen;
END_RCPP
}
// cpp_pseudobulk_metal
List cpp_pseudobulk_metal(SEXP x, IntegerVector unit, int n_units, double max_gpu_bytes);
RcppExport SEXP _extremarank_cpp_pseudobulk_metal(SEXP xSEXP, SEXP unitSEXP, SEXP n_unitsSEXP, SEXP max_gpu_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< double >::type max_gpu_bytes(max_gpu_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pseudobulk_metal(x, unit, n_units, max_gpu_bytes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_audit
List cpp_audit(NumericMatrix x, CharacterVector ids, CharacterVector unit_ids, IntegerVector labels, bool paired_design, int k, int budget, std::string direction, IntegerVector selected, int max_nodes, int max_scenarios, int witness_trials, bool use_bounds, bool influence_order);
RcppExport SEXP _extremarank_cpp_audit(SEXP xSEXP, SEXP idsSEXP, SEXP unit_idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP kSEXP, SEXP budgetSEXP, SEXP directionSEXP, SEXP selectedSEXP, SEXP max_nodesSEXP, SEXP max_scenariosSEXP, SEXP witness_trialsSEXP, SEXP use_boundsSEXP, SEXP influence_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type unit_ids(unit_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type budget(budgetSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type selected(selectedSEXP);
    Rcpp::traits::input_parameter< int >::type max_nodes(max_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type max_scenarios(max_scenariosSEXP);
    Rcpp::traits::input_parameter< int >::type witness_trials(witness_trialsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bounds(use_boundsSEXP);
    Rcpp::traits::input_parameter< bool >::type influence_order(influence_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_audit(x, ids, unit_ids, labels, paired_design, k, budget, direction, selected, max_nodes, max_scenarios, witness_trials, use_bounds, influence_order));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extrema
List cpp_extrema(NumericVector values, NumericVector included, int choose);
RcppExport SEXP _extremarank_cpp_extrema(SEXP valuesSEXP, SEXP includedSEXP, SEXP chooseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type included(includedSEXP);
    Rcpp::traits::input_parameter< int >::type choose(chooseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extrema(values, included, choose));
    return rcpp_result_gen;
END_RCPP
}
// cpp_evaluate
List cpp_evaluate(NumericMatrix x, CharacterVector ids, IntegerVector labels, bool paired_design, std::string direction, IntegerVector deleted);
RcppExport SEXP _extremarank_cpp_evaluate(SEXP xSEXP, SEXP idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP directionSEXP, SEXP deletedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type deleted(deletedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_evaluate(x, ids, labels, paired_design, direction, deleted));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bounds
List cpp_bounds(NumericMatrix x, CharacterVector ids, IntegerVector labels, bool paired_design, IntegerVector included, IntegerVector optional, IntegerVector needed);
RcppExport SEXP _extremarank_cpp_bounds(SEXP xSEXP, SEXP idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP includedSEXP, SEXP optionalSEXP, SEXP neededSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type included(includedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type optional(optionalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type needed(neededSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bounds(x, ids, labels, paired_design, included, optional, needed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_diagnostics
List cpp_diagnostics(NumericMatrix x, CharacterVector ids, CharacterVector unit_ids, IntegerVector labels, bool paired_design, int k, std::string direction, int max_diagnostics);
RcppExport SEXP _extremarank_cpp_diagnostics(SEXP xSEXP, SEXP idsSEXP, SEXP unit_idsSEXP, SEXP labelsSEXP, SEXP paired_designSEXP, SEXP kSEXP, SEXP directionSEXP, SEXP max_diagnosticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type unit_ids(unit_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< int >::type max_diagnostics(max_diagnosticsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_diagnostics(x, ids, unit_ids, labels, paired_design, k, direction, max_diagnostics));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plan
List cpp_plan(IntegerVector labels, bool paired_design, int budget);
RcppExport SEXP _extremarank_cpp_plan(SEXP labelsSEXP, SEXP paired_designSEXP, SEXP budgetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    Rcpp::traits::input_parameter< int >::type budget(budgetSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_plan(labels, paired_design, budget));
    return rcpp_result_gen;
END_RCPP
}
// cpp_block_plan
List cpp_block_plan(IntegerVector a, IntegerVector b, int budget, bool paired_design);
RcppExport SEXP _extremarank_cpp_block_plan(SEXP aSEXP, SEXP bSEXP, SEXP budgetSEXP, SEXP paired_designSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type budget(budgetSEXP);
    Rcpp::traits::input_parameter< bool >::type paired_design(paired_designSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_block_plan(a, b, budget, paired_design));
    return rcpp_result_gen;
END_RCPP
}
// cpp_remaining
std::string cpp_remaining(std::string planned, int completed);
RcppExport SEXP _extremarank_cpp_remaining(SEXP plannedSEXP, SEXP completedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type planned(plannedSEXP);
    Rcpp::traits::input_parameter< int >::type completed(completedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_remaining(planned, completed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_extremarank_cpp_validate_counts", (DL_FUNC) &_extremarank_cpp_validate_counts, 1},
    {"_extremarank_cpp_pseudobulk_native", (DL_FUNC) &_extremarank_cpp_pseudobulk_native, 3},
    {"_extremarank_cpp_group_codes", (DL_FUNC) &_extremarank_cpp_group_codes, 1},
    {"_extremarank_cpp_backend_info", (DL_FUNC) &_extremarank_cpp_backend_info, 0},
    {"_extremarank_cpp_pseudobulk_metal", (DL_FUNC) &_extremarank_cpp_pseudobulk_metal, 4},
    {"_extremarank_cpp_audit", (DL_FUNC) &_extremarank_cpp_audit, 14},
    {"_extremarank_cpp_extrema", (DL_FUNC) &_extremarank_cpp_extrema, 3},
    {"_extremarank_cpp_evaluate", (DL_FUNC) &_extremarank_cpp_evaluate, 6},
    {"_extremarank_cpp_bounds", (DL_FUNC) &_extremarank_cpp_bounds, 7},
    {"_extremarank_cpp_diagnostics", (DL_FUNC) &_extremarank_cpp_diagnostics, 8},
    {"_extremarank_cpp_plan", (DL_FUNC) &_extremarank_cpp_plan, 3},
    {"_extremarank_cpp_block_plan", (DL_FUNC) &_extremarank_cpp_block_plan, 4},
    {"_extremarank_cpp_remaining", (DL_FUNC) &_extremarank_cpp_remaining, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_extremarank(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
